trigger: none

stages:

# Stage 1 - BUILD
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    continueOnError: true

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'
    - script: python3 base-app/helloworld.py
    displayName: 'Run Hello World '

# Stage 2 - UNIT TEST
- stage: UnitTest
  jobs:
  - job: UnitTestJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: PythonScript@0
      inputs:
        scriptSource: 'inline'
        script: |
          pip install pytest pytest-azurepipelines
          pip install pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
      displayName: 'Unit Test with pytest'