trigger:
- main

pool:
  name: 'Default'  # Asegúrese de que este sea el nombre correcto de su pool de agentes auto-hosteados

steps:
- script: |
    python3 --version
    pip --version
  displayName: 'Verificar versiones de Python y pip'

- script: |
    python3 -m pip install --upgrade pip
    python3 -m pip install -r requirements.txt
  displayName: 'Actualizar pip e instalar dependencias'

- script: |
    python3 -m pytest tests/
  displayName: 'Ejecutar pruebas'

- script: |
    python3 app.py
  displayName: 'Ejecutar aplicación'