trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'srv-conn-azRM'
  acrLoginServer: 'acrinterviewdevops.azurecr.io'
  imageName: 'flaskapp'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Inicia sesión en ACR
          az acr login --name $(acrLoginServer)
          
          # Construye la imagen Docker
          docker build -t $(acrLoginServer)/$(imageName):$(tag) .
          
          # Empuja la imagen al registro de contenedores
          docker push $(acrLoginServer)/$(imageName):$(tag)